project_name: gitlab-runner-operator
builds:
  - env: [CGO_ENABLED=0]
    binary: operator
    goos:
      - linux
    goarch:
      - amd64
      - arm64
#dockers:
#  - image_templates: ["ghcr.io/alekc/gitlab-runner-operator-amd64"]
#    dockerfile: Dockerfile
#    use: buildx
#    build_flag_templates:
#      - --platform=linux/amd64
#      - --label=org.opencontainers.image.title={{ .ProjectName }}
#      - --label=org.opencontainers.image.description={{ .ProjectName }}
#      - --label=org.opencontainers.image.url=https://github.com/alekc/gitlab-runner-operator
#      - --label=org.opencontainers.image.source=https://github.com/alekc/gitlab-runner-operator
#      - --label=org.opencontainers.image.version={{ .Version }}
#      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#      - --label=org.opencontainers.image.revision={{ .FullCommit }}
#      - --label=org.opencontainers.image.licenses=Mozilla Public License Version 2.0
#  - image_templates: [ "ghcr.io/alekc/gitlab-runner-operator-arm64" ]
#    dockerfile: Dockerfile
#    goarch: arm64
#    use: buildx
#    build_flag_templates:
#      - --platform=linux/arm64/v8
#      - --label=org.opencontainers.image.title={{ .ProjectName }}
#      - --label=org.opencontainers.image.description={{ .ProjectName }}
#      - --label=org.opencontainers.image.url=https://github.com/alekc/gitlab-runner-operator
#      - --label=org.opencontainers.image.source=https://github.com/alekc/gitlab-runner-operator
#      - --label=org.opencontainers.image.version={{ .Version }}
#      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#      - --label=org.opencontainers.image.revision={{ .FullCommit }}
#      - --label=org.opencontainers.image.licenses=Mozilla Public License Version 2.0
#docker_manifests:
#  - name_template: ghcr.io/alekc/gitlab-runner-operator:{{ .Version }}
#    image_templates:
#      - "ghcr.io/alekc/gitlab-runner-operator-amd64"
#      - "ghcr.io/alekc/gitlab-runner-operator-arm64"