---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gitlab-k8s-alekc-dev-v1beta1-runner
  failurePolicy: Fail
  name: mrunner.kb.io
  rules:
  - apiGroups:
    - gitlab.k8s.alekc.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runners
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gitlab-k8s-alekc-dev-v1beta1-runner
  failurePolicy: Fail
  name: vrunner.kb.io
  rules:
  - apiGroups:
    - gitlab.k8s.alekc.dev
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - runners
  sideEffects: None
