name: dev-release

on: pull_request

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.17.x

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        id: ref_slug

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --timeout=1h
        env:
          VERSION: ${{  steps.ref_slug.outputs.github-ref-name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: set up buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build (and publish) main image
        env:
          DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/gitlab-runner-operator
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=pr-${GITHUB_REF_SLUG//-merge/} \
            --push \
            -t ${DOCKER_REPO}:pr-${GITHUB_REF_SLUG//-merge/} .
##            .
#          docker buildx build \
#            --platform linux/amd64,linux/arm64 \
#            --build-arg VERSION=latest \
#            --push \
#            -t ${DOCKER_REPO}:latest \
#            -f dockerfiles/endpoints-operator/Dockerfile \
#            .